### ISSUE TITLE
tipos de input incorrectos

### ISSUE THREAD

**Issue by kholostyak17** [Azumydori/FormHtml5Bootstrap#1]
El input del código postal debe de ser de tipo numérico en lugar de email:
https://github.com/Azumydori/FormHtml5Bootstrap/blob/89815a4988656b916a9614ca9a254ac989976ecd/index.html#L71

El botón de submit debe de ser un input de tipo submit en lugar de ser un botón, en este caso, los datos del formulario no se enviarían si este boton es presionado.
https://github.com/Azumydori/FormHtml5Bootstrap/blob/89815a4988656b916a9614ca9a254ac989976ecd/index.html#L112

**Comment by Azumydori** [comment]
Todo esto ya esta corregido
